name: tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: develop

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        go-version: [ "1.19" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      -
        name: setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ matrix.go-version }}
      -
        name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      -
        name: simple test
        run: go test -v ./...
      -
        name: test with GC pressure
        run: go test -v ./...
        env:
          GOGC: 1
      -
        name: test with race detector
        run: go test -v -race ./...
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: 1.19
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: measure coverage
        run: go test -v -coverprofile=coverage.out ./...
      - name: report coverage
        run: |
          bash <(curl -s https://codecov.io/bash)
